pub mod route;
pub mod simulated_annealing;
mod neighbor_move;
pub mod day;
pub mod week;
mod order_day_flags;
mod FIXTHISSHITANDWEAREDONE;
mod neighbor_chooser;
mod score_calculator;
pub mod solution;
mod order_location;